module.exports = {
  carosalMovies: [
    {
      movie_id: 101,
      title: "Avengers: Endgame",
      description:
        "After the devastating events of Avengers: Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.",
      duration_minutes: 181,
      release_date: "2019-04-26",
      genre: ["Action", "Adventure", "Drama"],
      rating: "PG-13",
      poster_url: "https://m.media-amazon.com/images/M/MV5BMTc5MDE2ODcwNV5BMl5BanBnXkFtZTgwMzI2NzQ2NzM@._V1_SX300.jpg",
      trailer_url: null,
      language: "English",
      country: "USA",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      status: "ACTIVE",
      director: "Anthony Russo, Joe Russo",
      synopsis:
        "After the devastating events of Avengers: Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.",
    },
    {
      movie_id: 102,
      title: "Spider-Man: No Way Home",
      description:
        "With Spider-Man's identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear, forcing Peter to discover what it truly means to be Spider-Man.",
      duration_minutes: 148,
      release_date: "2021-12-17",
      genre: ["Action", "Adventure", "Fantasy"],
      rating: "PG-13",
      poster_url:
        "https://m.media-amazon.com/images/M/MV5BZWMyYzFjYTYtNTRjYi00OGExLWE2YzgtOGRmYjAxZTU3NzBiXkEyXkFqcGdeQXVyMzQ0MzA0NTM@._V1_SX300.jpg",
      trailer_url: null,
      language: "English",
      country: "USA",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      status: "ACTIVE",
      director: "Jon Watts",
      synopsis:
        "With Spider-Man's identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear, forcing Peter to discover what it truly means to be Spider-Man.",
    },
    {
      movie_id: 103,
      title: "The Batman",
      description:
        "When a sadistic serial killer begins murdering key political figures in Gotham, Batman is forced to investigate the city's hidden corruption and question his family's involvement.",
      duration_minutes: 176,
      release_date: "2022-03-04",
      genre: ["Action", "Crime", "Drama"],
      rating: "PG-13",
      poster_url:
        "https://m.media-amazon.com/images/M/MV5BMDdmMTBiNTYtMDIzNi00NGVlLWIzMDYtZTk3MTQ3NGQxZGEwXkEyXkFqcGdeQXVyMzMwOTU5MDk@._V1_SX300.jpg",
      trailer_url: null,
      language: "English",
      country: "USA",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      status: "ACTIVE",
      director: "Matt Reeves",
      synopsis:
        "When a sadistic serial killer begins murdering key political figures in Gotham, Batman is forced to investigate the city's hidden corruption and question his family's involvement.",
    },
  ],

  upcomingMovies: [
    {
      movie_id: 111,
      title: "Guardians of the Galaxy Vol. 3",
      description:
        "Peter Quill, still reeling from the loss of Gamora, must rally his team around him to defend the universe along with protecting one of their own. A mission that, if not completed successfully, could quite possibly lead to the end of the Guardians as we know them.",
      duration_minutes: 150,
      release_date: "2023-05-05",
      genre: ["Action", "Adventure", "Comedy"],
      rating: "PG-13",
      poster_url:
        "https://m.media-amazon.com/images/M/MV5BMDgxOTdjMzYtZGQxMS00ZTAzLWI4Y2UtMTQzN2VlYjYyZWRiXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
      trailer_url: null,
      language: "English",
      country: "USA",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      status: "COMING_SOON",
      director: "James Gunn",
      synopsis:
        "Peter Quill, still reeling from the loss of Gamora, must rally his team around him to defend the universe along with protecting one of their own.",
    },
  ],

  movieList: [
    {
      movie_id: 101,
      title: "Avengers: Endgame",
      description:
        "After the devastating events of Avengers: Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.",
      poster_url: "https://m.media-amazon.com/images/M/MV5BMTc5MDE2ODcwNV5BMl5BanBnXkFtZTgwMzI2NzQ2NzM@._V1_SX300.jpg",
      backdrop: "https://image.tmdb.org/t/p/original/orjiB3oUIsyz60hoEqkiGpy5CeO.jpg",
      duration_minutes: 181,
      writers: ["Christopher Markus", "Stephen McFeely"],
      producers: ["Kevin Feige"],
      cinematography: "Trent Opaloch",
      music: "Alan Silvestri",
      budget: 356000000,
      release_date: "2019-04-26",
      genre: ["Action", "Adventure", "Drama"],
      language: "English",
      country: "USA",
      rating: "PG-13",
      status: "ACTIVE",
      trailer_url: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      movie_id: 102,
      title: "Spider-Man: No Way Home",
      description:
        "With Spider-Man's identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear, forcing Peter to discover what it truly means to be Spider-Man.",
      poster_url:
        "https://m.media-amazon.com/images/M/MV5BZWMyYzFjYTYtNTRjYi00OGExLWE2YzgtOGRmYjAxZTU3NzBiXkEyXkFqcGdeQXVyMzQ0MzA0NTM@._V1_SX300.jpg",
      backdrop: "https://image.tmdb.org/t/p/original/14QbnygCuTO0vl7CAFmPf1fgZfV.jpg",
      duration_minutes: 148,
      writers: ["Chris McKenna", "Erik Sommers"],
      producers: ["Kevin Feige", "Amy Pascal"],
      cinematography: "Mauro Fiore",
      music: "Michael Giacchino",
      budget: 200000000,
      release_date: "2021-12-17",
      genre: ["Action", "Adventure", "Fantasy"],
      language: "English",
      country: "USA",
      rating: "PG-13",
      status: "ACTIVE",
      trailer_url: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      movie_id: 103,
      title: "The Batman",
      description:
        "When a sadistic serial killer begins murdering key political figures in Gotham, Batman is forced to investigate the city's hidden corruption and question his family's involvement.",
      poster_url:
        "https://m.media-amazon.com/images/M/MV5BMDdmMTBiNTYtMDIzNi00NGVlLWIzMDYtZTk3MTQ3NGQxZGEwXkEyXkFqcGdeQXVyMzMwOTU5MDk@._V1_SX300.jpg",
      backdrop: "https://image.tmdb.org/t/p/original/b0PlSFdDwbyK0cf5RxwDpaOJQvQ.jpg",
      duration_minutes: 176,
      writers: ["Matt Reeves", "Peter Craig"],
      producers: ["Dylan Clark", "Matt Reeves"],
      cinematography: "Greig Fraser",
      music: "Michael Giacchino",
      budget: 185000000,
      release_date: "2022-03-04",
      genre: ["Action", "Crime", "Drama"],
      language: "English",
      country: "USA",
      rating: "PG-13",
      status: "ACTIVE",
      trailer_url: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      movie_id: 104,
      title: "Top Gun: Maverick",
      description:
        "After thirty years, Maverick is still pushing the envelope as a top naval aviator, but must confront ghosts of his past when he leads TOP GUN's elite graduates on a mission that demands the ultimate sacrifice from those chosen to fly it.",
      poster_url:
        "https://m.media-amazon.com/images/M/MV5BZWYzOGEwNTgtNWU3NS00ZTQ0LWJkODUtMmVhMjIwMjA1ZmQwXkEyXkFqcGdeQXVyMjkwOTAyMDU@._V1_SX300.jpg",
      backdrop: "https://image.tmdb.org/t/p/original/odJ4hx6g6vBt4lBWKFD1tI8WS4x.jpg",
      duration_minutes: 130,
      writers: ["Ehren Kruger", "Eric Warren Singer", "Christopher McQuarrie"],
      producers: ["Jerry Bruckheimer", "Tom Cruise"],
      cinematography: "Claudio Miranda",
      music: "Hans Zimmer",
      budget: 170000000,
      release_date: "2022-05-27",
      genre: ["Action", "Drama"],
      language: "English",
      country: "USA",
      rating: "PG-13",
      status: "ACTIVE",
      trailer_url: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      movie_id: 105,
      title: "Dune",
      description:
        "A mythic and emotionally charged hero's journey that tells the story of Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding.",
      poster_url:
        "https://m.media-amazon.com/images/M/MV5BN2FjNmEyNWMtYzM0ZS00NjIyLTg5YzYtYThlMGVjNzE1OGViXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
      backdrop: "https://image.tmdb.org/t/p/original/iopYFB1b6Bh7FWZh3onQhph1sih.jpg",
      duration_minutes: 155,
      writers: ["Jon Spaihts", "Denis Villeneuve", "Eric Roth"],
      producers: ["Mary Parent", "Denis Villeneuve", "Cale Boyter"],
      cinematography: "Greig Fraser",
      music: "Hans Zimmer",
      budget: 165000000,
      release_date: "2021-10-22",
      genre: ["Action", "Adventure", "Drama"],
      language: "English",
      country: "USA",
      rating: "PG-13",
      status: "ACTIVE",
      trailer_url: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      movie_id: 107,
      title: "Doctor Strange in the Multiverse of Madness",
      description:
        "Doctor Strange teams up with a mysterious teenage girl from his dreams who can travel across multiverses, to battle multiple threats, including other-universe versions of himself.",
      poster_url:
        "https://m.media-amazon.com/images/M/MV5BNWM0ZGJlMzMtZmYwMi00NzI3LTgzMzMtNjMzNjliNDRmZmFlXkEyXkFqcGdeQXVyMTM1MTE1NDMx._V1_SX300.jpg",
      backdrop: "https://image.tmdb.org/t/p/original/wcKFYIiVDvRURrzglV9kGu7fpfY.jpg",
      duration_minutes: 126,
      writers: ["Michael Waldron"],
      producers: ["Kevin Feige"],
      cinematography: "John Mathieson",
      music: "Danny Elfman",
      budget: 200000000,
      release_date: "2022-05-06",
      genre: ["Action", "Adventure", "Fantasy"],
      language: "English",
      country: "USA",
      rating: "PG-13",
      status: "ACTIVE",
      trailer_url: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      movie_id: 108,
      title: "Thor: Love and Thunder",
      description:
        "Thor enlists the help of Valkyrie, Korg and ex-girlfriend Jane Foster to fight Gorr the God Butcher, who intends to make the gods extinct.",
      poster_url:
        "https://m.media-amazon.com/images/M/MV5BYmMxZWRiMTgtZjM0Ny00NDQxLWIxYWQtZDdlNDNkOTEzYTdlXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
      backdrop: "https://image.tmdb.org/t/p/original/jsoz1HlxczSuTx0mDl2h0lxy36l.jpg",
      duration_minutes: 119,
      writers: ["Taika Waititi", "Jennifer Kent Robinson"],
      producers: ["Kevin Feige"],
      cinematography: "Barry Baz Idoine",
      music: "Michael Giacchino",
      budget: 250000000,
      release_date: "2022-07-08",
      genre: ["Action", "Adventure", "Comedy"],
      language: "English",
      country: "USA",
      rating: "PG-13",
      status: "ACTIVE",
      trailer_url: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      movie_id: 110,
      title: "Shang-Chi and the Legend of the Ten Rings",
      description:
        "Shang-Chi, the master of weaponry-based Kung Fu, is forced to confront his past after being drawn into the Ten Rings organization.",
      poster_url:
        "https://m.media-amazon.com/images/M/MV5BNTliYjlkNDQtMjFlNS00NjgzLWFmMWEtYmM2Mzc2Zjg3ZjEyXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
      backdrop: "https://image.tmdb.org/t/p/original/cinER0ESG0eJ49kXlExM0MEWGxW.jpg",
      duration_minutes: 132,
      writers: ["Dave Callaham", "Destin Daniel Cretton", "Andrew Lanham"],
      producers: ["Kevin Feige"],
      cinematography: "Bill Pope",
      music: "Joel P West",
      budget: 150000000,
      release_date: "2021-09-03",
      genre: ["Action", "Adventure", "Fantasy"],
      language: "English",
      country: "USA",
      rating: "PG-13",
      status: "ACTIVE",
      trailer_url: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ],
};
