module.exports = {
  carosalMovies: [
    {
      movie_id: 101,
      title: "Galactic Odyssey",
      description: "A team of astronauts embarks on a perilous journey through a newly discovered wormhole.",
      duration_minutes: 148,
      release_date: "2023-12-15",
      genre: ["Sci-Fi", "Adventure"],
      rating: "PG-13",
      poster_url: "https://image.tmdb.org/t/p/original/56v2KjBlU4XaOv9rVYEQypROD7P.jpg",
      trailer_url: null,
      language: "English",
      country: "USA",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      // Legacy fields for compatibility
      status: "COMING_SOON",
      director: "Ava Rodriguez",
      synopsis: "A team of astronauts embarks on a perilous journey through a newly discovered wormhole.",
    },
    {
      movie_id: 102,
      title: "Midnight Heist",
      description: "A crew of skilled thieves plans an impossible robbery during the summer solstice.",
      duration_minutes: 132,
      release_date: "2023-11-10",
      genre: ["Thriller", "Action"],
      rating: "R",
      poster_url:
        "https://img.onmanorama.com/content/dam/mm/en/entertainment/entertainment-news/images/2024/4/16/interstellar.jpg?w=1120&h=583",
      trailer_url: null,
      language: "English",
      country: "USA",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      // Legacy fields for compatibility
      status: "ACTIVE",
      director: "Jordan Peele",
      synopsis: "A crew of skilled thieves plans an impossible robbery during the summer solstice.",
    },
    {
      movie_id: 103,
      title: "The Last Summer",
      description: "A bittersweet coming-of-age story about three friends during their final summer before college.",
      duration_minutes: 118,
      release_date: "2024-02-14",
      genre: ["Romance", "Drama"],
      rating: "PG-13",
      poster_url:
        "https://cdn.shopify.com/s/files/1/0057/3728/3618/files/darkknight.building.24x36_20e90057-f673-4cc3-9ce7-7b0d3eeb7d83_500x749.jpg?v=1707491191",
      trailer_url: null,
      language: "English",
      country: "USA",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      // Legacy fields for compatibility
      status: "COMING_SOON",
      director: "Sophia Coppola",
      synopsis: "A bittersweet coming-of-age story about three friends during their final summer before college.",
    },
  ],

  upcomingMovies: [
    {
      movie_id: 105,
      title: "Galactic Odyssey",
      description: "A team of astronauts embarks on a perilous journey through a newly discovered wormhole.",
      duration_minutes: 148,
      release_date: "2023-12-15",
      genre: ["Sci-Fi", "Adventure"],
      rating: "PG-13",
      poster_url: "https://cdn.shopify.com/s/files/1/0057/3728/3618/files/avengers.24x36_500x749.jpg?v=1707410714",
      trailer_url: null,
      language: "English",
      country: "USA",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      // Legacy fields for compatibility
      status: "COMING_SOON",
      director: "Ava Rodriguez",
      synopsis: "A team of astronauts embarks on a perilous journey through a newly discovered wormhole.",
    },
  ],

  movieList: [
    {
      movie_id: 101,
      title: "Galactic Odyssey",
      description:
        "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces and one strange little girl.",
      poster_url: "https://cdn.shopify.com/s/files/1/0057/3728/3618/files/avengers.24x36_500x749.jpg?v=1707410714",
      backdrop: "https://image.tmdb.org/t/p/original/56v2KjBlU4XaOv9rVYEQypROD7P.jpg",
      duration_minutes: 180,
      writers: ["The Duffer Brothers", "Jessica Mecklenburg", "Justin Doble"],
      producers: ["Shawn Levy", "Dan Cohen", "Iain Paterson"],
      cinematography: "Tim Ives",
      music: "Kyle Dixon & Michael Stein",
      budget: 60000000,
      release_date: "2023-12-15",
      genre: ["Sci-Fi", "Adventure", "Mystery"],
      language: "English",
      country: "USA",
      rating: "PG-13",
      status: "ACTIVE",
      trailer_url: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      movie_id: 102,
      title: "Midnight Heist",
      description: "A crew of skilled thieves plans an impossible robbery during the summer solstice.",
      poster_url:
        "https://img.onmanorama.com/content/dam/mm/en/entertainment/entertainment-news/images/2024/4/16/interstellar.jpg?w=1120&h=583",
      backdrop: "https://image.tmdb.org/t/p/original/56v2KjBlU4XaOv9rVYEQypROD7P.jpg",
      duration_minutes: 132,
      writers: ["Jordan Peele", "Win Rosenfeld"],
      producers: ["Jordan Peele", "Jason Blum"],
      cinematography: "Toby Oliver",
      music: "Michael Abels",
      budget: 20000000,
      release_date: "2023-11-10",
      genre: ["Thriller", "Action", "Crime"],
      language: "English",
      country: "USA",
      rating: "R",
      status: "ACTIVE",
      trailer_url: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      movie_id: 103,
      title: "The Last Summer",
      description:
        "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces and one strange little girl.",
      poster_url:
        "https://cdn.shopify.com/s/files/1/0057/3728/3618/files/darkknight.building.24x36_20e90057-f673-4cc3-9ce7-7b0d3eeb7d83_500x749.jpg?v=1707491191",
      backdrop: "https://image.tmdb.org/t/p/original/56v2KjBlU4XaOv9rVYEQypROD7P.jpg",
      duration_minutes: 180,
      writers: ["The Duffer Brothers", "Jessica Mecklenburg", "Justin Doble"],
      producers: ["Shawn Levy", "Dan Cohen", "Iain Paterson"],
      cinematography: "Tim Ives",
      music: "Kyle Dixon & Michael Stein",
      budget: 60000000,
      release_date: "2024-02-14",
      genre: ["Romance", "Drama", "Coming-of-age"],
      language: "English",
      country: "USA",
      rating: "PG-13",
      status: "ACTIVE",
      trailer_url: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    // Additional sample movies for better home page display
    {
      movie_id: 201,
      title: "Avengers: Endgame",
      description: "The epic conclusion to the Infinity Saga.",
      poster_url: "/src/assets/images/default-movie.png",
      backdrop: "https://image.tmdb.org/t/p/original/56v2KjBlU4XaOv9rVYEQypROD7P.jpg",
      duration_minutes: 181,
      writers: ["Christopher Markus", "Stephen McFeely"],
      producers: ["Kevin Feige"],
      cinematography: "Trent Opaloch",
      music: "Alan Silvestri",
      budget: 356000000,
      release_date: "2019-04-26",
      genre: ["Action", "Adventure", "Drama"],
      language: "English",
      country: "USA",
      rating: "PG-13",
      status: "ACTIVE",
      trailer_url: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      movie_id: 202,
      title: "Spider-Man: No Way Home",
      description: "Spider-Man's identity is revealed to the entire world.",
      poster_url: "/src/assets/images/default-movie.png",
      backdrop: "https://image.tmdb.org/t/p/original/56v2KjBlU4XaOv9rVYEQypROD7P.jpg",
      duration_minutes: 148,
      writers: ["Chris McKenna", "Erik Sommers"],
      producers: ["Kevin Feige", "Amy Pascal"],
      cinematography: "Mauro Fiore",
      music: "Michael Giacchino",
      budget: 200000000,
      release_date: "2021-12-17",
      genre: ["Action", "Adventure", "Fantasy"],
      language: "English",
      country: "USA",
      rating: "PG-13",
      status: "ACTIVE",
      trailer_url: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      movie_id: 203,
      title: "The Batman",
      description: "Batman ventures into Gotham City's underworld.",
      poster_url: "/src/assets/images/default-movie.png",
      backdrop: "https://image.tmdb.org/t/p/original/56v2KjBlU4XaOv9rVYEQypROD7P.jpg",
      duration_minutes: 176,
      writers: ["Matt Reeves", "Peter Craig"],
      producers: ["Dylan Clark", "Matt Reeves"],
      cinematography: "Greig Fraser",
      music: "Michael Giacchino",
      budget: 185000000,
      release_date: "2022-03-04",
      genre: ["Action", "Crime", "Drama"],
      language: "English",
      country: "USA",
      rating: "PG-13",
      status: "ACTIVE",
      trailer_url: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      movie_id: 204,
      title: "Top Gun: Maverick",
      description: "After thirty years, Maverick is still pushing the envelope.",
      poster_url: "/src/assets/images/default-movie.png",
      backdrop: "https://image.tmdb.org/t/p/original/56v2KjBlU4XaOv9rVYEQypROD7P.jpg",
      duration_minutes: 130,
      writers: ["Ehren Kruger", "Eric Warren Singer", "Christopher McQuarrie"],
      producers: ["Jerry Bruckheimer", "Tom Cruise"],
      cinematography: "Claudio Miranda",
      music: "Lorne Balfe",
      budget: 170000000,
      release_date: "2022-05-27",
      genre: ["Action", "Drama"],
      language: "English",
      country: "USA",
      rating: "PG-13",
      status: "ACTIVE",
      trailer_url: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      movie_id: 205,
      title: "Dune",
      description: "A mythic and emotionally charged hero's journey.",
      poster_url: "/src/assets/images/default-movie.png",
      backdrop: "https://image.tmdb.org/t/p/original/56v2KjBlU4XaOv9rVYEQypROD7P.jpg",
      duration_minutes: 155,
      writers: ["Jon Spaihts", "Denis Villeneuve", "Eric Roth"],
      producers: ["Mary Parent", "Denis Villeneuve", "Cale Boyter"],
      cinematography: "Greig Fraser",
      music: "Hans Zimmer",
      budget: 165000000,
      release_date: "2021-10-22",
      genre: ["Action", "Adventure", "Drama"],
      language: "English",
      country: "USA",
      rating: "PG-13",
      status: "ACTIVE",
      trailer_url: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      movie_id: 206,
      title: "Black Widow",
      description: "Natasha Romanoff confronts the darker parts of her ledger.",
      poster_url: "/src/assets/images/default-movie.png",
      backdrop: "https://image.tmdb.org/t/p/original/56v2KjBlU4XaOv9rVYEQypROD7P.jpg",
      duration_minutes: 134,
      writers: ["Eric Pearson"],
      producers: ["Kevin Feige"],
      cinematography: "Gabriel Beristain",
      music: "Lorne Balfe",
      budget: 200000000,
      release_date: "2021-07-09",
      genre: ["Action", "Adventure", "Thriller"],
      language: "English",
      country: "USA",
      rating: "PG-13",
      status: "ACTIVE",
      trailer_url: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      movie_id: 207,
      title: "Doctor Strange in the Multiverse of Madness",
      description: "Doctor Strange travels into the multiverse.",
      poster_url: "/src/assets/images/default-movie.png",
      backdrop: "https://image.tmdb.org/t/p/original/56v2KjBlU4XaOv9rVYEQypROD7P.jpg",
      duration_minutes: 126,
      writers: ["Michael Waldron"],
      producers: ["Kevin Feige"],
      cinematography: "John Mathieson",
      music: "Danny Elfman",
      budget: 200000000,
      release_date: "2022-05-06",
      genre: ["Action", "Adventure", "Fantasy"],
      language: "English",
      country: "USA",
      rating: "PG-13",
      status: "ACTIVE",
      trailer_url: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      movie_id: 208,
      title: "Thor: Love and Thunder",
      description: "Thor attempts to find inner peace.",
      poster_url: "/src/assets/images/default-movie.png",
      backdrop: "https://image.tmdb.org/t/p/original/56v2KjBlU4XaOv9rVYEQypROD7P.jpg",
      duration_minutes: 119,
      writers: ["Taika Waititi", "Jennifer Kent Robinson"],
      producers: ["Kevin Feige"],
      cinematography: "Barry Baz Idoine",
      music: "Michael Giacchino",
      budget: 250000000,
      release_date: "2022-07-08",
      genre: ["Action", "Adventure", "Comedy"],
      language: "English",
      country: "USA",
      rating: "PG-13",
      status: "ACTIVE",
      trailer_url: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      movie_id: 209,
      title: "Eternals",
      description: "The saga of the Eternals spans thousands of years.",
      poster_url: "/src/assets/images/default-movie.png",
      backdrop: "https://image.tmdb.org/t/p/original/56v2KjBlU4XaOv9rVYEQypROD7P.jpg",
      duration_minutes: 157,
      writers: ["Chloé Zhao", "Patrick Burleigh"],
      producers: ["Kevin Feige"],
      cinematography: "Ben Davis",
      music: "Ramin Djawadi",
      budget: 200000000,
      release_date: "2021-11-05",
      genre: ["Action", "Adventure", "Drama"],
      language: "English",
      country: "USA",
      rating: "PG-13",
      status: "ACTIVE",
      trailer_url: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      movie_id: 210,
      title: "Shang-Chi and the Legend of the Ten Rings",
      description: "Shang-Chi must confront the past he thought he left behind.",
      poster_url: "/src/assets/images/default-movie.png",
      backdrop: "https://image.tmdb.org/t/p/original/56v2KjBlU4XaOv9rVYEQypROD7P.jpg",
      duration_minutes: 132,
      writers: ["Dave Callaham", "Destin Daniel Cretton", "Andrew Lanham"],
      producers: ["Kevin Feige"],
      cinematography: "Bill Pope",
      music: "Joel P West",
      budget: 150000000,
      release_date: "2021-09-03",
      genre: ["Action", "Adventure", "Fantasy"],
      language: "English",
      country: "USA",
      rating: "PG-13",
      status: "ACTIVE",
      trailer_url: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      movie_id: 211,
      title: "Fast & Furious 9",
      description: "Dom and the crew must take on an international terrorist.",
      poster_url: "/src/assets/images/default-movie.png",
      backdrop: "https://image.tmdb.org/t/p/original/56v2KjBlU4XaOv9rVYEQypROD7P.jpg",
      duration_minutes: 143,
      writers: ["Daniel Casey", "Justin Lin"],
      producers: ["Neal H. Moritz", "Vin Diesel", "Jeff Kirschenbaum"],
      cinematography: "Stephen F. Windon",
      music: "Brian Tyler",
      budget: 200000000,
      release_date: "2021-06-25",
      genre: ["Action", "Crime", "Thriller"],
      language: "English",
      country: "USA",
      rating: "PG-13",
      status: "ACTIVE",
      trailer_url: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      movie_id: 212,
      title: "No Time to Die",
      description: "James Bond has left active service.",
      poster_url: "/src/assets/images/default-movie.png",
      backdrop: "https://image.tmdb.org/t/p/original/56v2KjBlU4XaOv9rVYEQypROD7P.jpg",
      duration_minutes: 163,
      writers: ["Neal Purvis", "Robert Wade", "Cary Joji Fukunaga", "Phoebe Waller-Bridge"],
      producers: ["Michael G. Wilson", "Barbara Broccoli"],
      cinematography: "Linus Sandgren",
      music: "Hans Zimmer",
      budget: 250000000,
      release_date: "2021-10-08",
      genre: ["Action", "Adventure", "Thriller"],
      language: "English",
      country: "USA",
      rating: "PG-13",
      status: "ACTIVE",
      trailer_url: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      movie_id: 213,
      title: "Godzilla vs. Kong",
      description: "The epic next chapter in the cinematic Monsterverse.",
      poster_url: "/src/assets/images/default-movie.png",
      backdrop: "https://image.tmdb.org/t/p/original/56v2KjBlU4XaOv9rVYEQypROD7P.jpg",
      duration_minutes: 113,
      writers: ["Eric Pearson", "Max Borenstein"],
      producers: ["Thomas Tull", "Jon Jashni", "Brian Rogers"],
      cinematography: "Ben Seresin",
      music: "Junkie XL",
      budget: 200000000,
      release_date: "2021-03-31",
      genre: ["Action", "Sci-Fi", "Thriller"],
      language: "English",
      country: "USA",
      rating: "PG-13",
      status: "ACTIVE",
      trailer_url: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      movie_id: 214,
      title: "Mission: Impossible - Dead Reckoning",
      description: "Ethan Hunt and his team face their most impossible mission yet.",
      poster_url: "/src/assets/images/default-movie.png",
      backdrop: "https://image.tmdb.org/t/p/original/56v2KjBlU4XaOv9rVYEQypROD7P.jpg",
      duration_minutes: 163,
      writers: ["Christopher McQuarrie", "Erik Jendresen"],
      producers: ["Tom Cruise", "Christopher McQuarrie"],
      cinematography: "Fraser Taggart",
      music: "Lorne Balfe",
      budget: 290000000,
      release_date: "2023-07-12",
      genre: ["Action", "Adventure", "Thriller"],
      language: "English",
      country: "USA",
      rating: "PG-13",
      status: "ACTIVE",
      trailer_url: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      movie_id: 215,
      title: "John Wick: Chapter 4",
      description: "John Wick uncovers a path to defeating The High Table.",
      poster_url: "/src/assets/images/default-movie.png",
      backdrop: "https://image.tmdb.org/t/p/original/56v2KjBlU4XaOv9rVYEQypROD7P.jpg",
      duration_minutes: 169,
      writers: ["Shay Hatten", "Michael Finch"],
      producers: ["Basil Iwanyk", "Erica Lee", "Chad Stahelski"],
      cinematography: "Dan Laustsen",
      music: "Tyler Bates",
      budget: 100000000,
      release_date: "2023-03-24",
      genre: ["Action", "Crime", "Thriller"],
      language: "English",
      country: "USA",
      rating: "R",
      status: "ACTIVE",
      trailer_url: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      movie_id: 216,
      title: "Inception",
      description: "A thief who steals corporate secrets through dream-sharing.",
      poster_url: "/src/assets/images/default-movie.png",
      backdrop: "https://image.tmdb.org/t/p/original/56v2KjBlU4XaOv9rVYEQypROD7P.jpg",
      duration_minutes: 148,
      writers: ["Christopher Nolan"],
      producers: ["Emma Thomas", "Christopher Nolan"],
      cinematography: "Wally Pfister",
      music: "Hans Zimmer",
      budget: 160000000,
      release_date: "2010-07-16",
      genre: ["Action", "Sci-Fi", "Thriller"],
      language: "English",
      country: "USA",
      rating: "PG-13",
      status: "ACTIVE",
      trailer_url: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      movie_id: 217,
      title: "Interstellar",
      description: "A team of explorers travel through a wormhole in space.",
      poster_url: "/src/assets/images/default-movie.png",
      backdrop: "https://image.tmdb.org/t/p/original/56v2KjBlU4XaOv9rVYEQypROD7P.jpg",
      duration_minutes: 169,
      writers: ["Jonathan Nolan", "Christopher Nolan"],
      producers: ["Emma Thomas", "Christopher Nolan", "Lynda Obst"],
      cinematography: "Hoyte van Hoytema",
      music: "Hans Zimmer",
      budget: 165000000,
      release_date: "2014-11-07",
      genre: ["Adventure", "Drama", "Sci-Fi"],
      language: "English",
      country: "USA",
      rating: "PG-13",
      status: "ACTIVE",
      trailer_url: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      movie_id: 218,
      title: "The Dark Knight",
      description: "Batman raises the stakes in his war on crime.",
      poster_url: "/src/assets/images/default-movie.png",
      backdrop: "https://image.tmdb.org/t/p/original/56v2KjBlU4XaOv9rVYEQypROD7P.jpg",
      duration_minutes: 152,
      writers: ["Jonathan Nolan", "Christopher Nolan"],
      producers: ["Emma Thomas", "Charles Roven", "Christopher Nolan"],
      cinematography: "Wally Pfister",
      music: "Hans Zimmer",
      budget: 185000000,
      release_date: "2008-07-18",
      genre: ["Action", "Crime", "Drama"],
      language: "English",
      country: "USA",
      rating: "PG-13",
      status: "ACTIVE",
      trailer_url: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      movie_id: 219,
      title: "Avatar: The Way of Water",
      description: "Jake Sully lives with his newfound family formed on Pandora.",
      poster_url: "/src/assets/images/default-movie.png",
      backdrop: "https://image.tmdb.org/t/p/original/56v2KjBlU4XaOv9rVYEQypROD7P.jpg",
      duration_minutes: 192,
      writers: ["James Cameron", "Rick Jaffa", "Amanda Silver"],
      producers: ["James Cameron", "Jon Landau"],
      cinematography: "Russell Carpenter",
      music: "Simon Franglen",
      budget: 460000000,
      release_date: "2022-12-16",
      genre: ["Action", "Adventure", "Fantasy"],
      language: "English",
      country: "USA",
      rating: "PG-13",
      status: "ACTIVE",
      trailer_url: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      movie_id: 220,
      title: "Guardians of the Galaxy Vol. 3",
      description: "Peter Quill must rally his team for a dangerous mission.",
      poster_url: "/src/assets/images/default-movie.png",
      backdrop: "https://image.tmdb.org/t/p/original/56v2KjBlU4XaOv9rVYEQypROD7P.jpg",
      duration_minutes: 150,
      writers: ["James Gunn"],
      producers: ["Kevin Feige"],
      cinematography: "Henry Braham",
      music: "John Murphy",
      budget: 250000000,
      release_date: "2023-05-05",
      genre: ["Action", "Adventure", "Comedy"],
      language: "English",
      country: "USA",
      rating: "PG-13",
      status: "ACTIVE",
      trailer_url: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ],
};
